# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: Any path below can be absolute (e.g. "/var/myawesomeapp/data") or
# relative to the home directory (e.g. "data"). The home directory is
# "$HOME/.tendermint" by default, but could be changed via $TMHOME env variable
# or --home cmd flag.

#######################################################
###     Multiseed Server Configuration Options      ###
#######################################################
# Port for the frontend
http_port = "8090"

# Chain specific config
[terra]
[p2p]
chain_id = "columbus-5"
bootstrap-peers = "e999fc20aa5b87c1acef8677cf495ad85061cfb9@seed.terra.delightlabs.io:26656,6d8e943c049a80c161a889cb5fcf3d184215023e@public-seed2.terra.dev:26656,87048bf71526fb92d73733ba3ddb79b7a83ca11e@public-seed.terra.dev:26656,66aa2bac58b137e17865035567fc85f06953d4af@terra-seed01.stakers.finance:26656"
laddr = "tcp://0.0.0.0:26656"
